development:
  adapter: postgresql
  encoding: unicode
  database: tracker_dev
  pool: 5
  username: bloc
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: tracker_test
  pool: 5
  username: bloc
  password: password

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000