development:
  adapter: postgresql
  encoding: unicode
  database: tracker_dev
  pool: 5
  username: bloc
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: tracker_test
  pool: 5
  username: bloc
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: tracker_pro
  pool: 5
  username: bloc
  password: password